import 'dart:convert';

import 'package:flutter/material.dart';

import 'ip_address.dart';
import 'package:http/http.dart' as http;

class TestSelect extends StatelessWidget {
  const TestSelect({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    String muscle = "복근";
    String equipment = "맨몸";
    String difficulty = "초보자";

    return Scaffold(
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                select(muscle, equipment, difficulty);
              },
              child: Text('데이터 가져오기~'),
            )
          ],
        ),
      ),
    );
  }

  Future select(String muscle, String equipment, String difficulty) async {
    var url = Uri.http(IP_ADDRESS, '/test_select.php', {'q': '{http}'});
    var response = await http.post(url, body: <String, String>{
      "muscle": muscle.toString(),
      "equipment": equipment.toString(),
      "difficulty": difficulty.toString(),
    });
    var stringdata = json.decode(json.encode(response.body));
    var jsondata = jsonDecode(stringdata);
    //print(jsondata.runtimeType);
    //print(jsondata['result'].runtimeType);
    //print(jsondata['result'][0].runtimeType);
    //print(jsondata['result'][0]['step'].runtimeType);

    Result data = Result.fromJson(jsondata);
    //print(data.runtimeType);
    //print(data.muscle);

    Autogenerated data2 = Autogenerated.fromJson(jsondata);
    print(data2.runtimeType);
    print(data2.result.runtimeType); //가져온 데이터 전체
    print(data2.result!.length); //가져온 데이터가 몇 개인가?
    print(data2.result![0].muscle); //첫 번째 데이터의 근육


    /*
    final realdata = jsondata['result']
        .map((x) => Result(
              muscle: x['muscle'].toString(),
              equipment: x['equipment'].toString(),
              difficulty: x['difficulty'].toString(),
              exercise: x['exercise'].toString(),
              image1: x['image1'].toString(),
              image2: x['image2'].toString(),
              step: x['step'].toString(),
            ))
        .toList();

    print(realdata.runtimeType);
    print(realdata.muscle);

     */
  }
}

class Autogenerated {
  List<Result>? result;

  Autogenerated({this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      result = <Result>[];
      json['result'].forEach((v) {
        result!.add(new Result.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Result {
  String? muscle;
  String? equipment;
  String? difficulty;
  String? exercise;
  String? image1;
  String? image2;
  String? step;

  Result(
      {this.muscle,
      this.equipment,
      this.difficulty,
      this.exercise,
      this.image1,
      this.image2,
      this.step});

  Result.fromJson(Map<String, dynamic> json) {
    muscle = json['muscle'];
    equipment = json['equipment'];
    difficulty = json['difficulty'];
    exercise = json['exercise'];
    image1 = json['image1'];
    image2 = json['image2'];
    step = json['step'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['muscle'] = this.muscle;
    data['equipment'] = this.equipment;
    data['difficulty'] = this.difficulty;
    data['exercise'] = this.exercise;
    data['image1'] = this.image1;
    data['image2'] = this.image2;
    data['step'] = this.step;
    return data;
  }
}
