/*
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:test_exercise_guide/const/set_exercise.dart';
import 'package:http/http.dart' as http;

import '../screen/exercise_guide.dart';
import 'ip_address.dart';

class SearchName extends StatelessWidget {
  final name;
  final level;
  const SearchName({
    required this.name,
    required this.level,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Map<String, int> mapExNum = {
      "이두": 1,
      "가슴": 2,
      '대퇴 사두근': 3,
      '승모근': 4,
      '삼두': 5,
      '어깨': 6,
      '광배근': 7,
      '대퇴 이두근': 8,
      '둔근': 9,
      '전완근': 10,
      '종아리': 11,
      '복근': 12,
      '등 하부': 13,
      '등 중앙부': 14,
      '복사근': 15
    };

    return Card(
      elevation: 0,
      child: ListTile(
        title: Text(name),
        onTap: () {
          final tmpLst = setExercise(mapExNum[name]!, level, '맨몸');

          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (BuildContext context) => ExerciseGuide(
                muscleName: tmpLst[0],
                exerciseName: tmpLst[1],
                exerciseImage1: tmpLst[2],
                exerciseImage2: tmpLst[3],
                equipment: tmpLst[4],
                level: tmpLst[5],
                exerciseStep: tmpLst[6],
                difficulty: tmpLst[7],
              ),
            ),
          );
        },
      ),
    );
  }

  Future select(String muscle, String equipment, String difficulty) async {
    var url = Uri.http(IP_ADDRESS, '/test_select.php', {'q': '{http}'});
    var response = await http.post(url, body: <String, String>{
      "muscle": muscle.toString(),
      "equipment": equipment.toString(),
      "difficulty": difficulty.toString(),
    });
    var stringdata = json.decode(json.encode(response.body));
    var jsondata = jsonDecode(stringdata);
    //print(jsondata.runtimeType);
    //print(jsondata['result'].runtimeType);
    //print(jsondata['result'][0].runtimeType);
    //print(jsondata['result'][0]['step'].runtimeType);

    Result data = Result.fromJson(jsondata);
    //print(data.runtimeType);
    //print(data.muscle);

    Autogenerated data2 = Autogenerated.fromJson(jsondata);
    print(data2.runtimeType);
    print(data2.result.runtimeType); //가져온 데이터 전체
    print(data2.result!.length); //가져온 데이터가 몇 개인가?
    print(data2.result![0].muscle); //첫 번째 데이터의 근육

    /*
    final realdata = jsondata['result']
        .map((x) => Result(
              muscle: x['muscle'].toString(),
              equipment: x['equipment'].toString(),
              difficulty: x['difficulty'].toString(),
              exercise: x['exercise'].toString(),
              image1: x['image1'].toString(),
              image2: x['image2'].toString(),
              step: x['step'].toString(),
            ))
        .toList();

    print(realdata.runtimeType);
    print(realdata.muscle);

     */
  }
}

class Autogenerated {
  List<Result>? result;

  Autogenerated({this.result});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['result'] != null) {
      result = <Result>[];
      json['result'].forEach((v) {
        result!.add(new Result.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Result {
  String? muscle;
  String? equipment;
  String? difficulty;
  String? exercise;
  String? image1;
  String? image2;
  String? step;

  Result(
      {this.muscle,
      this.equipment,
      this.difficulty,
      this.exercise,
      this.image1,
      this.image2,
      this.step});

  Result.fromJson(Map<String, dynamic> json) {
    muscle = json['muscle'];
    equipment = json['equipment'];
    difficulty = json['difficulty'];
    exercise = json['exercise'];
    image1 = json['image1'];
    image2 = json['image2'];
    step = json['step'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['muscle'] = this.muscle;
    data['equipment'] = this.equipment;
    data['difficulty'] = this.difficulty;
    data['exercise'] = this.exercise;
    data['image1'] = this.image1;
    data['image2'] = this.image2;
    data['step'] = this.step;
    return data;
  }
}

 */